# Generated by Django 4.2.20 on 2025-05-07 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('street_name', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(default='Reykjavik', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('type', models.CharField(default='Apartment', max_length=50)),
                ('listing_price', models.PositiveIntegerField()),
                ('is_sold', models.BooleanField(default=False)),
                ('listing_date', models.DateField(auto_now_add=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apartments.apartment')),
            ],
        ),
    ]
