# Generated by Django 4.0.4 on 2025-05-12 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_seller_apartment_num_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.seller'),
        ),
    ]
