# Generated by Django 4.2.20 on 2025-05-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_alter_apartment_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='apartmentimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
