# Generated by Django 4.2.20 on 2025-05-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_alter_apartmentimage_options_apartmentimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentimage',
            options={'ordering': ['image_url']},
        ),
    ]
