# Generated by Django 4.0.4 on 2025-05-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_alter_apartmentimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
